language: java

sudo: false

jdk: oraclejdk8

branches:
  only:
  - master
  - dev

script: ./gradlew check

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

after_success:
- >
  test $TRAVIS_PULL_REQUEST = "false" &&
    ./gradlew buildPlugin &&
    curl -i --header "Authorization: Bearer $TOKEN" \
         -F xmlId=intellij-clock \
         -F file=@$(ls -d1 build/distributions/*) \
         -F channel=Stable \
         https://plugins.jetbrains.com/plugin/uploadPlugin
